//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        public Documents()
        {
            this.Sentences = new HashSet<Sentences>();
        }
    
        public System.Guid Document_ID { get; set; }
        public string Link { get; set; }
    
        public virtual ICollection<Sentences> Sentences { get; set; }
    }
}
