//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedWords
    {
        public System.Guid RelatedWords_ID { get; set; }
        public System.Guid Sentence_FID { get; set; }
        public string word1 { get; set; }
        public string word2 { get; set; }
        public int Count { get; set; }
    
        public virtual Sentences Sentences { get; set; }
    }
}
