//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindRelations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sentences
    {
        public Sentences()
        {
            this.RelatedWords = new HashSet<RelatedWords>();
        }
    
        public System.Guid Sentence_ID { get; set; }
        public System.Guid Document_FID { get; set; }
        public string Sentence { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual ICollection<RelatedWords> RelatedWords { get; set; }
    }
}
